<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Employee_status extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Employee_status_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $this->template->general('employee_status/emp_status_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Employee_status_model->json();
    }

    public function read($id)
    {
        $row = $this->Employee_status_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Read',
                'action' => 'read',
                'id' => $row->id,
                'emp_desc' => $row->emp_desc,
            );
            $this->template->general('employee_status/emp_status_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('employee_status'));
        }
    }

    public function create()
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('employee_status/create_action'),
            'id' => set_value('id'),
            'emp_desc' => set_value('emp_desc'),
        );
        $this->template->general('employee_status/emp_status_form', $data);
    }

    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'emp_desc' => $this->input->post('emp_desc', TRUE),
            );

            $this->Employee_status_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('employee_status'));
        }
    }

    public function update($id)
    {
        $row = $this->Employee_status_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('employee_status/update_action'),
                'id' => set_value('id', $row->id),
                'emp_desc' => set_value('emp_desc', $row->emp_desc),
            );
            $this->template->general('employee_status/emp_status_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('employee_status'));
        }
    }

    public function update_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'emp_desc' => $this->input->post('emp_desc', TRUE),
            );

            $this->Employee_status_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('employee_status'));
        }
    }

    public function delete($id)
    {
        $row = $this->Employee_status_model->get_by_id($id);

        if ($row) {
            $this->Employee_status_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('employee_status'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('employee_status'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('emp_desc', 'emp desc', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Employee_status.php */
/* Location: ./application/controllers/Employee_status.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-14 15:38:03 */
/* http://harviacode.com */