<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Loan_type extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Loan_type_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->general('loan_type/loan_type_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Loan_type_model->json();
    }

    public function read($id) 
    {
        $row = $this->Loan_type_model->get_by_id($id);
        if ($row) {
            $data = array(
				'button' => 'Read',
				'action' => 'read',
		'id' => $row->id,
		'name' => $row->name,
		'maxloan' => $row->maxloan,
	    );
            $this->template->general('loan_type/loan_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('loan_type'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('loan_type/create_action'),
	    'id' => set_value('id'),
	    'name' => set_value('name'),
	    'maxloan' => set_value('maxloan'),
	);
        $this->template->general('loan_type/loan_type_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'maxloan' => $this->input->post('maxloan',TRUE),
	    );

            $this->Loan_type_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('loan_type'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Loan_type_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('loan_type/update_action'),
		'id' => set_value('id', $row->id),
		'name' => set_value('name', $row->name),
		'maxloan' => set_value('maxloan', $row->maxloan),
	    );
            $this->template->general('loan_type/loan_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('loan_type'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'name' => $this->input->post('name',TRUE),
		'maxloan' => $this->input->post('maxloan',TRUE),
	    );

            $this->Loan_type_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('loan_type'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Loan_type_model->get_by_id($id);

        if ($row) {
            $this->Loan_type_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('loan_type'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('loan_type'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('name', 'name', 'trim|required');
	$this->form_validation->set_rules('maxloan', 'maxloan', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Loan_type.php */
/* Location: ./application/controllers/Loan_type.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-09 09:56:20 */
/* http://harviacode.com */