<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Locatsetup extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Locat_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->template->general('locatsetup/comp_locat_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Locat_model->json();
    }

    public function read($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Locat_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Read',
                'action' => 'read',
                'id' => $row->id,
                'locat_desc' => $row->locat_desc,
            );
            $this->template->general('locatsetup/comp_locat_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('locatsetup'));
        }
    }

    public function create()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $data = array(
            'button' => 'Create',
            'action' => site_url('locatsetup/create_action'),
            'id' => set_value('id'),
            'locat_desc' => set_value('locat_desc'),
        );
        $this->template->general('locatsetup/comp_locat_form', $data);
    }

    public function create_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'locat_desc' => $this->input->post('locat_desc', TRUE),
            );

            $this->Locat_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('locatsetup'));
        }
    }

    public function update($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Locat_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('locatsetup/update_action'),
                'id' => set_value('id', $row->id),
                'locat_desc' => set_value('locat_desc', $row->locat_desc),
            );
            $this->template->general('locatsetup/comp_locat_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('locatsetup'));
        }
    }

    public function update_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'locat_desc' => $this->input->post('locat_desc', TRUE),
            );

            $this->Locat_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('locatsetup'));
        }
    }

    public function delete($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Locat_model->get_by_id($id);

        if ($row) {
            $this->Locat_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('locatsetup'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('locatsetup'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('locat_desc', 'locat desc', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Locatsetup.php */
/* Location: ./application/controllers/Locatsetup.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-02 15:18:22 */
/* http://harviacode.com */