<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ministrysetup extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Ministry_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->template->general('ministrysetup/emp_ministry_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Ministry_model->json();
    }

    public function read($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Ministry_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Read',
                'action' => 'read',
                'id' => $row->id,
                'name' => $row->name,
            );
            $this->template->general('ministrysetup/emp_ministry_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ministrysetup'));
        }
    }

    public function create()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $data = array(
            'button' => 'Create',
            'action' => site_url('ministrysetup/create_action'),
            'id' => set_value('id'),
            'name' => set_value('name'),
        );
        $this->template->general('ministrysetup/emp_ministry_form', $data);
    }

    public function create_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'name' => $this->input->post('name', TRUE),
            );

            $this->Ministry_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('ministrysetup'));
        }
    }

    public function update($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Ministry_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('ministrysetup/update_action'),
                'id' => set_value('id', $row->id),
                'name' => set_value('name', $row->name),
            );
            $this->template->general('ministrysetup/emp_ministry_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ministrysetup'));
        }
    }

    public function update_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'name' => $this->input->post('name', TRUE),
            );

            $this->Ministry_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('ministrysetup'));
        }
    }

    public function delete($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Ministry_model->get_by_id($id);

        if ($row) {
            $this->Ministry_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('ministrysetup'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('ministrysetup'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('name', 'name', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Ministrysetup.php */
/* Location: ./application/controllers/Ministrysetup.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-02 12:09:58 */
/* http://harviacode.com */