<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Payrollsetup extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Payrollsetup_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->general('payrollsetup/emp_allowance_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Payrollsetup_model->json();
    }

    public function read($id) 
    {
        $row = $this->Payrollsetup_model->get_by_id($id);
        if ($row) {
            $data = array(
				'button' => 'Read',
				'action' => 'read',
		'id' => $row->id,
		'emp_no' => $row->emp_no,
		'allow_name' => $row->allow_name,
	    );
            $this->template->general('payrollsetup/emp_allowance_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('payrollsetup'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('payrollsetup/create_action'),
	    'id' => set_value('id'),
	    'emp_no' => set_value('emp_no'),
	    'allow_name' => set_value('allow_name'),
	);
        $this->template->general('payrollsetup/emp_allowance_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'emp_no' => $this->input->post('emp_no',TRUE),
		'allow_name' => $this->input->post('allow_name',TRUE),
	    );

            $this->Payrollsetup_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('payrollsetup'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Payrollsetup_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('payrollsetup/update_action'),
		'id' => set_value('id', $row->id),
		'emp_no' => set_value('emp_no', $row->emp_no),
		'allow_name' => set_value('allow_name', $row->allow_name),
	    );
            $this->template->general('payrollsetup/emp_allowance_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('payrollsetup'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
		'emp_no' => $this->input->post('emp_no',TRUE),
		'allow_name' => $this->input->post('allow_name',TRUE),
	    );

            $this->Payrollsetup_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('payrollsetup'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Payrollsetup_model->get_by_id($id);

        if ($row) {
            $this->Payrollsetup_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('payrollsetup'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('payrollsetup'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('emp_no', 'emp no', 'trim|required');
	$this->form_validation->set_rules('allow_name', 'allow name', 'trim|required');

	$this->form_validation->set_rules('id', 'id', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Payrollsetup.php */
/* Location: ./application/controllers/Payrollsetup.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-07 10:36:47 */
/* http://harviacode.com */