<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Reimsetup extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Reim_type_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->template->general('reimsetup/reim_type_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Reim_type_model->json();
    }

    public function read($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Reim_type_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Read',
                'action' => 'read',
                'id' => $row->id,
                'reim_desc' => $row->reim_desc,
            );
            $this->template->general('reimsetup/reim_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('reimsetup'));
        }
    }

    public function create()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $data = array(
            'button' => 'Create',
            'action' => site_url('reimsetup/create_action'),
            'id' => set_value('id'),
            'reim_desc' => set_value('reim_desc'),
        );
        $this->template->general('reimsetup/reim_type_form', $data);
    }

    public function create_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'reim_desc' => $this->input->post('reim_desc', TRUE),
            );

            $this->Reim_type_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('reimsetup'));
        }
    }

    public function update($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Reim_type_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('reimsetup/update_action'),
                'id' => set_value('id', $row->id),
                'reim_desc' => set_value('reim_desc', $row->reim_desc),
            );
            $this->template->general('reimsetup/reim_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('reimsetup'));
        }
    }

    public function update_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'reim_desc' => $this->input->post('reim_desc', TRUE),
            );

            $this->Reim_type_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('reimsetup'));
        }
    }

    public function delete($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Reim_type_model->get_by_id($id);

        if ($row) {
            $this->Reim_type_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('reimsetup'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('reimsetup'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('reim_desc', 'reim desc', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Reimsetup.php */
/* Location: ./application/controllers/Reimsetup.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-02 14:53:32 */
/* http://harviacode.com */