<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Resource_type extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Resource_type_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->template->general('resource_type/book_type_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Resource_type_model->json();
    }

    public function read($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Resource_type_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Read',
                'action' => 'read',
                'id' => $row->id,
                'type_desc' => $row->type_desc,
            );
            $this->template->general('resource_type/book_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('resource_type'));
        }
    }

    public function create()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $data = array(
            'button' => 'Create',
            'action' => site_url('resource_type/create_action'),
            'id' => set_value('id'),
            'type_desc' => set_value('type_desc'),
        );
        $this->template->general('resource_type/book_type_form', $data);
    }

    public function create_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'type_desc' => $this->input->post('type_desc', TRUE),
            );

            $this->Resource_type_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('resource_type'));
        }
    }

    public function update($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Resource_type_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('resource_type/update_action'),
                'id' => set_value('id', $row->id),
                'type_desc' => set_value('type_desc', $row->type_desc),
            );
            $this->template->general('resource_type/book_type_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('resource_type'));
        }
    }

    public function update_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'type_desc' => $this->input->post('type_desc', TRUE),
            );

            $this->Resource_type_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('resource_type'));
        }
    }

    public function delete($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Resource_type_model->get_by_id($id);

        if ($row) {
            $this->Resource_type_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('resource_type'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('resource_type'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('type_desc', 'type desc', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Resource_type.php */
/* Location: ./application/controllers/Resource_type.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-14 13:25:00 */
/* http://harviacode.com */