<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Taskcatsetup extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Taskcategory_model');
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->template->general('taskcatsetup/task_category_list');
    }

    public function json()
    {
        header('Content-Type: application/json');
        echo $this->Taskcategory_model->json();
    }

    public function read($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Taskcategory_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Read',
                'action' => 'read',
                'id' => $row->id,
                'category_name' => $row->category_name,
            );
            $this->template->general('taskcatsetup/task_category_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('taskcatsetup'));
        }
    }

    public function create()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $data = array(
            'button' => 'Create',
            'action' => site_url('taskcatsetup/create_action'),
            'id' => set_value('id'),
            'category_name' => set_value('category_name'),
        );
        $this->template->general('taskcatsetup/task_category_form', $data);
    }

    public function create_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'category_name' => $this->input->post('category_name', TRUE),
            );

            $this->Taskcategory_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(site_url('taskcatsetup'));
        }
    }

    public function update($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Taskcategory_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('taskcatsetup/update_action'),
                'id' => set_value('id', $row->id),
                'category_name' => set_value('category_name', $row->category_name),
            );
            $this->template->general('taskcatsetup/task_category_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('taskcatsetup'));
        }
    }

    public function update_action()
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'category_name' => $this->input->post('category_name', TRUE),
            );

            $this->Taskcategory_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('taskcatsetup'));
        }
    }

    public function delete($id)
    {
        if (isExistClassMenu() == FALSE) {
            redirect(site_url('dashboard'));
        }

        $row = $this->Taskcategory_model->get_by_id($id);

        if ($row) {
            $this->Taskcategory_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('taskcatsetup'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('taskcatsetup'));
        }
    }

    public function _rules()
    {
        $this->form_validation->set_rules('category_name', 'category name', 'trim|required');

        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }
}

/* End of file Taskcatsetup.php */
/* Location: ./application/controllers/Taskcatsetup.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-02 15:45:07 */
/* http://harviacode.com */