<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Att_history_model extends CI_Model
{

    public $table = 'absen';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json($emp_no, $start, $length)
    {
        /*
        $this->datatables->select('absen.id,employee.emp_name as emp_no,start_time,end_time,ot,lunch_out,lunch_in,type');
        $this->datatables->from('absen');

        $this->datatables->join('employee', 'absen.emp_no = employee.emp_no','left');
        $this->datatables->add_column('action', '','id');
        return $this->datatables->generate();
*/

        $qry = $this->get_list_by_emp_no($emp_no, $start, $length);

        if (count($qry) > 0) {
            $res = '{"draw":0,"recordsTotal":' . $this->get_total_by_emp_no($emp_no) . ', "recordsFiltered":' . $this->get_total_by_emp_no($emp_no) . ',"data":[';
            foreach ($qry as $row => $val) {
                $res .= '{';
                foreach ($val as $key => $value) {
                    $res .= '"' . $key . '":"' . $value . '",';
                }
                $res .= '"action":""';
                $res .= '},';
            }
            $res = substr($res, 0, strlen($res) - 1);
            $res .= ']}';
        } else {
            $res = '{"draw":0,"recordsTotal":0,"recordsFiltered":0,"data":[]}';
        }

        json_decode($res);
        return $res;
    }

    function get_list_by_emp_no($empno, $start, $length)
    {
        $this->db->select('absen.id,employee.emp_name as emp_no,start_time,end_time,ot,lunch_out,lunch_in,type');
        if ($empno != null) $this->db->where('absen.emp_no', $empno);
        $this->db->join('employee', 'absen.emp_no = employee.emp_no', 'left');
        $this->db->limit($length, $start);
        return $this->db->get($this->table)->result();
    }

    function get_total_by_emp_no($empno)
    {
        $this->db->select('absen.id,employee.emp_name as emp_no,start_time,end_time,ot,lunch_out,lunch_in,type');
        $this->db->from('absen');
        if ($empno != null) $this->db->where('absen.emp_no', $empno);
        $this->db->join('employee', 'absen.emp_no = employee.emp_no', 'left');
        return $this->db->count_all_results();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('emp_no', $q);
        $this->db->or_like('start_time', $q);
        $this->db->or_like('end_time', $q);
        $this->db->or_like('ot', $q);
        $this->db->or_like('lunch_out', $q);
        $this->db->or_like('lunch_in', $q);
        $this->db->or_like('type', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('emp_no', $q);
        $this->db->or_like('start_time', $q);
        $this->db->or_like('end_time', $q);
        $this->db->or_like('ot', $q);
        $this->db->or_like('lunch_out', $q);
        $this->db->or_like('lunch_in', $q);
        $this->db->or_like('type', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Att_history_model.php */
/* Location: ./application/models/Att_history_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-18 23:44:00 */
/* http://harviacode.com */