<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_attempt_model extends CI_Model
{
    public $table = 'uc_login_attempt';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_email($email, $ipAddress)
    {
        $this->db->where(['email' => $email, 'ip_address' => $ipAddress]);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('ip_address', $q);
        $this->db->or_like('limit_login_attempt', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('ip_address', $q);
        $this->db->or_like('limit_login_attempt', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // only update status
    function update_attempt($email, $attempt)
    {
        $this->db->set('limit_login_attempt', $attempt);
        $this->db->where('email', $email);
        $this->db->update($this->table);
    }

    // only update status
    function update_inc_dec_attempt($email, $ip_address, $data)
    {
        $this->db->where('email', $email);
        $this->db->where('ip_address', $ip_address);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Mst_client_model.php */
/* Location: ./application/models/Mst_client_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-13 13:04:50 */
/* http://harviacode.com */