<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login_model extends CI_Model
{
    public $table = 'uc_users';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json()
    {
        $this->datatables->select('mst_client.ID,number,desc as type,name,DATE_FORMAT(dob,\'%d %M %Y\') as dob,gender,mobile,email,address,city,nation,state,photo,num_of_payment,init_amount,transdate');
        $this->datatables->from('mst_client');
        //add this line for join
        $this->datatables->join('mst_insurance_type', 'mst_client.type = mst_insurance_type.ID');
        $this->datatables->add_column('action', anchor(site_url('client/read/$1'), '<i class="btn btn-sm btn-info fa fa-clone"></i>') . "&nbsp;&nbsp;&nbsp;" . anchor(site_url('client/update/$1'), '<i class="btn btn-sm btn-info fa fa-pencil"></i>') . "&nbsp;&nbsp;&nbsp;" .
            '<a class="btn btn-sm btn-danger" href="#" onClick="var action = \'delete\'; var page = \'Client\'; var url = \'client/delete/$1\'; var id = \'$1\';  confirmation(action,page,url,id); "><i class="fa fa-trash"></i></a>', 'ID');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_email($email)
    {
        $this->db->where('email', $email);
        return $this->db->get($this->table)->row();
    }

    function get_attempt($email)
    {
        $this->db->where('email', $email);
        return $this->db->get($this->table)->row();
    }

    function PassCheck($email, $pass)
    {
        $this->db->join('employee', 'uc_users.id=employee.login_id', 'left');
        $this->db->where(array('uc_users.email' => $email, 'uc_users.password' => md5($pass)));
        // 		$this->db->get($this->table);
        // 		print_r($this->db->last_query());die;
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('ID', $q);
        $this->db->or_like('number', $q);
        $this->db->or_like('type', $q);
        $this->db->or_like('name', $q);
        $this->db->or_like('dob', $q);
        $this->db->or_like('gender', $q);
        $this->db->or_like('mobile', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('address', $q);
        $this->db->or_like('city', $q);
        $this->db->or_like('nation', $q);
        $this->db->or_like('state', $q);
        $this->db->or_like('photo', $q);
        $this->db->or_like('num_of_payment', $q);
        $this->db->or_like('init_amount', $q);
        $this->db->or_like('transdate', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID', $q);
        $this->db->or_like('number', $q);
        $this->db->or_like('type', $q);
        $this->db->or_like('name', $q);
        $this->db->or_like('dob', $q);
        $this->db->or_like('gender', $q);
        $this->db->or_like('mobile', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('address', $q);
        $this->db->or_like('city', $q);
        $this->db->or_like('nation', $q);
        $this->db->or_like('state', $q);
        $this->db->or_like('photo', $q);
        $this->db->or_like('num_of_payment', $q);
        $this->db->or_like('init_amount', $q);
        $this->db->or_like('transdate', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // only update status
    function update_status($email, $status = 'N')
    {
        $this->db->set('locked_account_status', $status);
        $this->db->where('email', $email);
        $this->db->update($this->table);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Mst_client_model.php */
/* Location: ./application/models/Mst_client_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-13 13:04:50 */
/* http://harviacode.com */