<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mst_insurance_type_model extends CI_Model
{

    public $table = 'mst_insurance_type';
    public $id = 'ID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('ID,desc,active');
        $this->datatables->from('mst_insurance_type');
        $this->datatables->where('active','1');
        //add this line for join
        //$this->datatables->join('table2', 'mst_insurance_type.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('transtype/read/$1'),'<i class="btn btn-sm btn-info fa fa-clone"></i>'), 'ID');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('active', '1');
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
		$this->db->where('active', '1');
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('ID', $q);
	$this->db->or_like('desc', $q);
	$this->db->from($this->table);
	$this->db->where('active', '1');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
		$this->db->where('active', '1');
        $this->db->order_by($this->id, $this->order);
        $this->db->like('ID', $q);
		$this->db->or_like('desc', $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mst_insurance_type_model.php */
/* Location: ./application/models/Mst_insurance_type_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-13 16:26:17 */
/* http://harviacode.com */