<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Mydisciple_model extends CI_Model
{

    public $table = 'emp_disciple';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,disciple_no,emp_no,disciple_category,disciple_date,sdate,edate,remark');
        $this->datatables->from('emp_disciple');
        $this->datatables->where('emp_no',$this->session->userdata('emp_no'));
        //add this line for join
        //$this->datatables->join('table2', 'emp_disciple.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('mydisciple/read/$1'),'<i class="btn btn-sm btn-info fa fa-clone"></i>')."&nbsp;&nbsp;&nbsp;",'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('disciple_no', $q);
	$this->db->or_like('emp_no', $q);
	$this->db->or_like('disciple_category', $q);
	$this->db->or_like('disciple_date', $q);
	$this->db->or_like('sdate', $q);
	$this->db->or_like('edate', $q);
	$this->db->or_like('remark', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('disciple_no', $q);
	$this->db->or_like('emp_no', $q);
	$this->db->or_like('disciple_category', $q);
	$this->db->or_like('disciple_date', $q);
	$this->db->or_like('sdate', $q);
	$this->db->or_like('edate', $q);
	$this->db->or_like('remark', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Mydisciple_model.php */
/* Location: ./application/models/Mydisciple_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-07 09:31:06 */
/* http://harviacode.com */