<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Myloan_model extends CI_Model
{

    public $table = 'emp_loan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,emp_no,requestdate,type,amount,startpayment,remark,loanprocess,installmentamount,loanperiod,interest,totalpayment,balance');
        $this->datatables->from('emp_loan');
        //add this line for join
        //$this->datatables->join('table2', 'emp_loan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('myloan/read/$1'),'<i class="btn btn-sm btn-info fa fa-clone"></i>')."&nbsp;&nbsp;&nbsp;".anchor(site_url('myloan/update/$1'),'<i class="btn btn-sm btn-info fa fa-pencil"></i>')."&nbsp;&nbsp;&nbsp;".
			'<a class="btn btn-sm btn-danger" href="#" onClick="var action = \'delete\'; var page = \'emp_loan\'; var url = \'myloan/delete/$1\'; var id = \'$1\';  confirmation(action,page,url,id); "><i class="fa fa-trash"></i></a>','id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('emp_no', $q);
	$this->db->or_like('requestdate', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('startpayment', $q);
	$this->db->or_like('remark', $q);
	$this->db->or_like('loanprocess', $q);
	$this->db->or_like('installmentamount', $q);
	$this->db->or_like('loanperiod', $q);
	$this->db->or_like('interest', $q);
	$this->db->or_like('totalpayment', $q);
	$this->db->or_like('balance', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('emp_no', $q);
	$this->db->or_like('requestdate', $q);
	$this->db->or_like('type', $q);
	$this->db->or_like('amount', $q);
	$this->db->or_like('startpayment', $q);
	$this->db->or_like('remark', $q);
	$this->db->or_like('loanprocess', $q);
	$this->db->or_like('installmentamount', $q);
	$this->db->or_like('loanperiod', $q);
	$this->db->or_like('interest', $q);
	$this->db->or_like('totalpayment', $q);
	$this->db->or_like('balance', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Myloan_model.php */
/* Location: ./application/models/Myloan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-01-09 09:40:18 */
/* http://harviacode.com */