<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Policyoffer_model extends CI_Model
{

    public $table = 'policy';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('policy.id as id,mst_category.category as id_cat,mst_sub_category.sub_desc as id_subcat,policy_name,sum_assured,premium,tenure,policy.status,policy.created_date,(select count(id) from policy_applied where policy_applied.policy_id=policy.id and policy_applied.client_id=4) as applied');
        $this->datatables->from('policy');
        //add this line for join
        $this->datatables->join('mst_category', 'policy.id_cat=mst_category.id');
        $this->datatables->join('mst_sub_category', 'mst_category.id=mst_sub_category.id_cat and policy.id_subcat=mst_sub_category.id');
        // $this->datatables->add_column('action',"<button class=\"btn btn-danger btn-anim\" onclick=\"window.location.href='".base_url()."index.php/policyoffer/apply/$1'\"><i class=\"fa fa-pencil-square-o\"></i><span class=\"btn-text\">Apply</span></button>",'id');
        return $this->datatables->generate();
    }

    function get_detail_by_id($id) {
        $this->db->select('policy.id as id,mst_category.category as id_cat,mst_sub_category.sub_desc as id_subcat,policy_name,sum_assured,premium,tenure,policy.status,policy.created_date');
        $this->db->from('policy');
        $this->db->join('mst_category', 'policy.id_cat=mst_category.id','left');
        $this->db->join('mst_sub_category', 'mst_category.id=mst_sub_category.id_cat and policy.id_subcat=mst_sub_category.id','left');
		$this->db->where('policy.id', $id);
		$ret = $this->db->get()->row();
        return $ret;
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_cat', $q);
	$this->db->or_like('id_subcat', $q);
	$this->db->or_like('policy_name', $q);
	$this->db->or_like('sum_assured', $q);
	$this->db->or_like('premium', $q);
	$this->db->or_like('tenure', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('created_date', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('id_cat', $q);
	$this->db->or_like('id_subcat', $q);
	$this->db->or_like('policy_name', $q);
	$this->db->or_like('sum_assured', $q);
	$this->db->or_like('premium', $q);
	$this->db->or_like('tenure', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('created_date', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

	function confirmed_by_id($policy_id,$client_id)
	{
		$exist = $this->db->query("select count(id) as jml from policy_applied where policy_id = '".$policy_id."' and client_id = '".$client_id."' ")->row();

		if ($exist->jml == 0)
		{
			$this->db->query("insert into policy_applied (client_id,policy_id) values ('".$client_id."','".$policy_id."')");
			return 'ok';
		} else {
			return 'exists';
		}
	}
}

/* End of file Policyoffer_model.php */
/* Location: ./application/models/Policyoffer_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-10-14 15:07:19 */
/* http://harviacode.com */